---
#
# 使い方:
#   TARGET_HOST=10.x.x.x
#   MAIN_USERNAME=username
#   MAIN_PASSWORD=password
#   DOCROOT=/var/www/html/htdocs
#   DBROOT=/opt/rh/mysql55/root/var/lib/mysql
#   PERMIT_NETWORK=10.0.0.0/255.0.0.0
#   CAKE_ENV_MODE=development
#   env ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i <(echo ${TARGET_HOST}) -u root -k site.yml \
#     --extra-vars "main_username=${MAIN_USERNAME} main_password=`openssl passwd -salt salty -1 ${MAIN_PASSWORD}` docroot=${DOCROOT} dbroot=${DBROOT} permit_network=${PERMIT_NETWORK} cake_env_mode=${CAKE_ENV_MODE}"
# 備考:
#   - TARGET_HOSTは設定対象のホストのIPアドレスを指定してください
#     rootでsshに接続しようとします
#   - MAIN_USERNAMEで指定した名前のユーザ・グループが作成されます
#     パスワードはMAIN_PASSWORDの値になります
#   - DOCROOTで指定したディレクトリがApacheのDocumentRootとなります
#     ディレクトリの所有者・所有グループはMAIN_USERNAMEで指定したものになります
#   - PHP OPcacheはソースからコンパイルしてインストールされています
#     PHP APCはインストールされません(PHP 5.4は未対応のため)
#   - CAKE_ENV_MODEで指定した値が環境変数CAKE_ENV_MODEの値に設定されます
#   - DBROOTで指定したディレクトリがMySQLのデータディレクトリとなります
#   - PERMIT_NETWORKで指定したネットワーク範囲からMySQLに接続可能です
#   - MySQLには、ID/PASS:root/rootでアクセスできます
#
- name: for CakePHP on LAMP (CentOS 6.5, MySQL 5.5, PHP 5.4) Ver. 20140313
  hosts: all
  user: root
  roles:
    - { role: centos6-common, main_username: "{{ main_username }}", main_password: "{{ main_password }}" }
    - { role: centos6-apache, main_username: "{{ main_username }}", docroot: "{{ docroot }}", cake_env_mode: "{{ cake_env_mode }}" }
    - { role: centos6-scl-php54 }
    - { role: centos6-scl-mysql55, dbroot: "{{ dbroot }}", permit_network: "{{ permit_network }}" }
